"""upgrade Category and Transaction model

Revision ID: 51606d9f8c26
Revises: 3fb477b26ed6
Create Date: 2025-01-06 16:39:46.780395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51606d9f8c26'
down_revision: Union[str, None] = '3fb477b26ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('comment', sa.String(), nullable=False))
    op.drop_constraint('transactions_caregory_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'caregory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('caregory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_caregory_id_fkey', 'transactions', 'categories', ['caregory_id'], ['id'])
    op.drop_column('transactions', 'comment')
    # ### end Alembic commands ###
