"""upgrade Category and Transaction model

Revision ID: 2cdec30156f6
Revises: 3fb477b26ed6
Create Date: 2025-01-06 20:11:44.835061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2cdec30156f6"
down_revision: Union[str, None] = "3fb477b26ed6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("comment", sa.String(), nullable=True))
    op.add_column(
        "transactions",
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
    )
    op.drop_constraint(
        "transactions_caregory_id_fkey", "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "caregory_id")
    op.drop_column("transactions", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("caregory_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transactions_caregory_id_fkey",
        "transactions",
        "categories",
        ["caregory_id"],
        ["id"],
    )
    op.drop_column("transactions", "date")
    op.drop_column("transactions", "comment")
    # ### end Alembic commands ###
