"""add __repr__ to models

Revision ID: 673951ffc5a8
Revises: 6aaa84925875
Create Date: 2025-01-05 16:29:26.035685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "673951ffc5a8"
down_revision: Union[str, None] = "6aaa84925875"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
